#!/bin/bash

TARGET=$1

# clone RMG-tests:
git clone https://github.com/ReactionMechanismGenerator/RMG-tests.git
cp RMG-tests/examples/rmg/$1/*.py .

INP=input.py

echo "Running $1 example"

# activate benchmark environment:
source activate benchmark

# set the BENCHMARK_RMG environment variable to the path with the rmg.py binary:
BENCHMARK_RMG=$CONDA_ENV_PATH/bin
echo "Benchmark version of RMG: "$BENCHMARK_RMG

# make folder for models generated by the benchmark version of RMG-Py and RMG-database:
mkdir -p benchmark
rm -rf benchmark/*
cp $INP benchmark/

echo "Generating model with benchmark version of RMG-Py..."
python $BENCHMARK_RMG/rmg.py benchmark/$INP > /dev/null